apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zqvgck0ey-python 
  janus-idp.io/tekton: zqvgck0ey-python
  backstage.io/kubernetes-id: zqvgck0ey-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zqvgck0ey-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml